name: Feature Request
description: Suggest an improvement for Relay
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature you'd like to see.
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: How would this feature help you?
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Any alternative solutions you've considered?
